### ISSUE TITLE
Generate Isochrones not working in QGIS Graphical Modeler

### ISSUE THREAD

**Issue by ChalktyGeo** [nilsnolde/orstools-qgis-plugin#107]
When trying to incorporate the Generate Isochrones tool in QGIS graphical modeler it is not possible due to the error raised with the "Input Point from map canvas option".

Please see my example below to help explain the issue:

![Test2](https://user-images.githubusercontent.com/48433421/57917502-b5a8bd80-788c-11e9-8010-5cdd9d8d9775.gif)

Unless I am misunderstanding the functionality I don't think there is a way around this - I would like to be able to specify the point layer input to run the isochrones but the canvas option is somehow stopping that.

Cheers

**Comment by nilsnolde** [comment]
Thanks for reporting this and the gif. I'll have a look next week, should be a minor fix.

**Comment by nilsnolde** [comment]
This doesn't seem to be a bug really. 

You didn't specify any API key, right? You'll have to go to 'Web' menu > ORS Tools > Provider Settings and specify one. I fixed the message though. In the normal Processing Toolbox, you get the algorithm help window on the right side by default, which would tell you to specify an API key. However, in the Graphical Modeler it doesn't show. Maybe you can flag that at QGIS repo. Also, the whole dialog is quite a bit different in the Modeler compared to the Processing toolbox tools.

**Comment by ChalktyGeo** [comment]
Even after specifying a valid API key it is still not possible for me to incorporate this into a model.

**Comment by ChalktyGeo** [comment]
Apologies, I can if I delete the "None" from the second dialogue box but how do you keep the option to add a point from the canvas?

**Comment by nilsnolde** [comment]
> how do you keep the option to add a point from the canvas?
Sorry, what do you mean? You want to have the 'point from map' option within the Modeler? That won't be possible I guess right?

Like I said, modeler and processing dialogs are different here. Just open the Isochrone window from the normal plugin GUI and you'll see what I mean. That field is not pre-filled with `None`. No idea why they differ.
